- hosts: unicorn
  become: true
  vars_files:
    - vars/main.yml
  pre_tasks:
    - name: Install required packages via APT
      apt:
        name:
          - acl
          - nginx
          - g++
          - make
          - autoconf
          - automake
          - bison
          - libffi-dev
          - libgdbm-dev
          - libncurses5-dev
          - libsqlite3-dev
          - libtool
          - libyaml-dev
          - pkg-config
          - sqlite3
          - zlib1g-dev
          - libgmp-dev
          - libreadline-dev
          - libssl-dev
          - libpq-dev
        update_cache: yes
        state: present
    - name: create user workshop
      user:
        name: "{{ app_user }}"
        shell: /bin/bash
  roles:
    - role: geerlingguy.nodejs
    - role: ocha.yarn
    - role: rvm.ruby
  tasks:
    - name: Deploy nginx config
      template:
        src: templates/etc/nginx/sites-enabled/workshop
        dest: /etc/nginx/sites-enabled/workshop
    - name: Remove default nginx config if exists
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Deploy systemd unit
      template:
        src: templates/etc/systemd/system/workshop-unicorn.service.j2
        dest: /etc/systemd/system/workshop-unicorn.service
    - name: Run systemctl daemon-reload
      systemd:
        daemon_reload: yes
    - name: enable service
      systemd:
        name: workshop-unicorn
        enabled: yes
